# particle_engine_supreme/particle_presets.py
"""
# Copyright (c) 2025 Joshua Kitchens
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
"""

EFFECT_PRESETS = {
    "rain": {
        "count": 3, "interval": 1, "duration": -1, "life_min": 120, "life_max": 180,
        "emitter_type": "rect", "use_custom_rect": False,
        "gravity": 0.9, "wind": 0.2, "drag": 0.0,
        "speed_min": 10, "speed_max": 15, "angle_min": 85, "angle_max": 95,
        "shape": "rect", "size_min": 2, "size_max": 3, "spin_min": 0, "spin_max": 0,
        "color": ["#a8d8ea"], "color_curve": None,
        "tint_image": False, "blend_mode": "normal",
        "trail_length": 10, "trail_width": 2, "trail_opacity": 100,
        "collides": True, "elasticity": 0.1, "friction": 0.1, "accumulate": False,
        "on_collide_effect": "splash"
    },
    "snow": {
        "count": 6, "interval": 1, "duration": -1, "life_min": 180, "life_max": 300,
        "emitter_type": "rect", "use_custom_rect": False,
        "gravity": 0.05, "wind": 0.05, "drag": 0.02,
        "speed_min": 1, "speed_max": 2, "angle_min": 0, "angle_max": 360,
        "shape": "image", "image_path": "particles/glow.png", "tint_image": True,
        "size_min": 2, "size_max": 3, "spin_min": -2, "spin_max": 2,
        "color": ["#FFFFFF"], "color_curve": None,
        "blend_mode": "add",
        "scale_curve": [1.0, 1.0, 1.0, 1.0, 0.9],
        "alpha_curve": [255, 255, 255, 255, 200],
        "behaviors": ["turbulence", "mouse_interaction"], 
        "mouse_mode": "repel",
        "mouse_strength": 2.0,
        "mouse_radius": 200,
        "mouse_falloff": "smooth",
        "turbulence_strength": 0.2, "turbulence_freq": 0.05,
        "collides": False, "accumulate": True
    },
    "fire": {
        "count": 5, "interval": 1, "duration": -1, "life_min": 30, "life_max": 60,
        "emitter_type": "point", "use_custom_rect": True,
        "gravity": -0.6, "drag": 0.05,
        "speed_min": 2, "speed_max": 5, "angle_min": -45, "angle_max": 45,
        "shape": "image", "image_path": "particles/glow.png", "tint_image": True,
        "size_min": 30, "size_max": 60, "spin_min": -8, "spin_max": 8,
        "color": ["#ffaa00"],
        "color_curve": ["#ffffaa", "#ffaa00", "#ff4400", "#ff0000", "#660000"],
        "alpha_curve": [0, 255, 200, 100, 0],
        "scale_curve": [0.4, 1.2, 1.0, 0.5, 0.1],
        "blend_mode": "add", "collides": False
    },
    "inferno": {
        "count": 8, "interval": 1, "duration": -1, "life_min": 20, "life_max": 45,
        "emitter_type": "cone", "cone_direction": 270, "cone_angle": 30, "use_custom_rect": True,
        "gravity": -0.8, "drag": 0.05,
        "speed_min": 5, "speed_max": 10,
        "shape": "circle", "size_min": 15, "size_max": 35,
        "color": ["#ff0000"],
        "color_curve": ["#FFFF00", "#FF4400", "#AA0000", "#000000"],
        "alpha_curve": [255, 255, 200, 0],
        "scale_curve": [0.5, 1.5, 1.0, 0.0],
        "blend_mode": "add", "collides": False
    },
    "smoke": {
        "count": 1, "interval": 5, "duration": -1, "life_min": 80, "life_max": 120,
        "emitter_type": "point", "use_custom_rect": True,
        "gravity": -0.15, "drag": 0.03,
        "speed_min": 0.5, "speed_max": 1.5, "angle_min": -30, "angle_max": 30,
        "shape": "image", "image_path": "particles/smoke.png", "tint_image": True,
        "color": ["#666666", "#999999"], "color_curve": None,
        "blend_mode": "normal",
        "alpha_curve": [0, 180, 120, 0, 0],
        "scale_curve": [0.5, 1.5, 2.5, 3.5, 4.0],
        "behaviors": ["turbulence"], "turbulence_strength": 0.1, "turbulence_freq": 0.05,
        "collides": False
    },
    "sparkles": {
        "count": 2, "interval": 2, "duration": -1, "life_min": 20, "life_max": 40,
        "emitter_type": "circle", "use_custom_rect": False,
        "gravity": 0.1, "drag": 0.1,
        "speed_min": 0, "speed_max": 1,
        "shape": "star", "star_points": 4, "size_min": 5, "size_max": 15,
        "spin_min": -5, "spin_max": 5,
        "color": ["#FFFFFF", "#FFFFaa"], "color_curve": None,
        "blend_mode": "add",
        "scale_curve": [0.0, 1.0, 1.0, 0.0],
        "alpha_curve": [0, 255, 255, 0]
    },
    "magic": {
        "count": 3, "interval": 2, "duration": -1, "life_min": 40, "life_max": 80,
        "emitter_type": "point", "use_custom_rect": True,
        "gravity": -0.2, "drag": 0.02,
        "speed_min": 1, "speed_max": 3, "angle_min": 0, "angle_max": 360,
        "shape": "star", "star_points": 5, "size_min": 10, "size_max": 20,
        "color": ["#FF00FF"], 
        "color_curve": ["#FFFFFF", "#FF00FF", "#AA00AA", "#000000"],
        "blend_mode": "add",
        "scale_curve": [0.5, 1.2, 0.0],
        "behaviors": ["orbit"], "orbit_speed": 0.1
    },
    "confetti": {
        "count": 5, "interval": 1, "duration": -1, "life_min": 60, "life_max": 120,
        "emitter_type": "rect", "use_custom_rect": False,
        "gravity": 0.4, "drag": 0.03, "wind": 0.1,
        "speed_min": 5, "speed_max": 10, "angle_min": 0, "angle_max": 360,
        "shape": "rect", "size_min": 5, "size_max": 15, "spin_min": -10, "spin_max": 10,
        "color": ["#ff0000", "#00ff00", "#0000ff", "#ffff00", "#ff00ff"], "color_curve": None,
        "blend_mode": "normal",
        "alpha_curve": [255, 255, 200, 150, 100],
        "collides": True, "elasticity": 0.6, "friction": 0.4
    },
    "bubbles": {
        "count": 2, "interval": 3, "duration": -1, "life_min": 100, "life_max": 200,
        "emitter_type": "rect", "use_custom_rect": False,
        "gravity": -0.15, "drag": 0.02,
        "speed_min": 1, "speed_max": 3, "angle_min": -20, "angle_max": 20,
        "shape": "bubble", "size_min": 10, "size_max": 30,
        "color": ["#88ccff"], "color_curve": None,
        "blend_mode": "add",
        "alpha_curve": [0, 150, 120, 100, 0],
        "scale_curve": [0.5, 1.0, 1.1, 1.0, 0.9],
        "behaviors": ["turbulence"], "turbulence_strength": 0.2, "turbulence_freq": 0.05
    },
    "energy": {
        "count": 4, "interval": 1, "duration": -1, "life_min": 30, "life_max": 50,
        "emitter_type": "circle", "use_custom_rect": True,
        "gravity": 0, "drag": 0.05,
        "speed_min": 2, "speed_max": 5,
        "shape": "circle", "size_min": 5, "size_max": 15,
        "color": ["#00FFFF"], 
        "color_curve": ["#FFFFFF", "#00FFFF", "#0088FF", "#000000"],
        "blend_mode": "add",
        "behaviors": ["turbulence"], "turbulence_strength": 0.5
    },
    "explosion": {
        "count": 50, "interval": 999, "duration": 1, "life_min": 30, "life_max": 60,
        "emitter_type": "point", "use_custom_rect": True,
        "gravity": 0.0, "drag": 0.1,
        "radial_accel": 10.0, "tangential_accel": 0.0,
        "speed_min": 2, "speed_max": 5, "angle_min": 0, "angle_max": 360,
        "shape": "circle", "size_min": 5, "size_max": 12,
        "color": ["#FFFFFF"],
        "color_curve": ["#ffffff", "#ffaa00", "#ff4400", "#660000"],
        "alpha_curve": [255, 255, 100, 0],
        "scale_curve": [1.0, 0.8, 0.4, 0.1],
        "blend_mode": "add", "collides": False
    },
    "matrix": { 
        'accumulate': False, 'align_rotation': False, 'alpha_curve': [255, 255, 255, 255, 255],
        'angle_max': 90.0, 'angle_min': 90.0, 'anim_speed': 1.0, 'attraction_radius': 200.0,
        'attraction_strength': 0.5, 'behaviors': ['mouse_interaction'], 'blend_mode': 'add',
        'collides': False, 
        'color': ['#00FF00'], 
        'color_curve': ['#2fff00', '#67ff6c', '#dcffdc'],
        'count': 4, 'drag': 0.05, 'duration': -1, 'elasticity': 0.7, 'emitter_h': 10, 'emitter_type': 'rect',
        'emitter_w': 10, 'emitter_x': 400, 'emitter_y': 300, 'friction': 0.5, 'gravity': 0.3000,
        'hue_variance': 0.0, 'image_path': '', 'interval': 5, 'life_max': 240, 'life_min': 180,
        'mouse_click_only': True,'mouse_falloff': 'smooth', 'mouse_mode': 'attract', 'mouse_radius': 300.0,
        'mouse_strength': 3.0, 'on_collide_effect': None, 'on_death_effect': None, 'orbit_speed': 0.05,
        'radial_accel': 0.0, 'random_start_frame': False, 'sat_variance': 0.0, 'scale_curve': [1.0, 1.0],
        'shape': 'text', 'size_max': 26.0, 'size_min': 20.0, 'speed_max': 6.0, 'speed_min': 4.0,
        'spin_max': 0.0, 'spin_min': -0.0, 'sprite_cols': 1, 'sprite_rows': 1, 'star_points': 5,
        'start_delay': 0, 'tangential_accel': 0.0, 'tint_image': True, 'trail_length': 2,
        'text_chars': 'ﾊﾐﾋｰｳｼﾅﾓﾆｻﾜﾂｵﾘｱｶｷﾑﾕﾗｾﾈｽﾀﾇﾍｦﾃｳﾍﾗｺﾄﾉｱﾎﾘﾑﾕﾗﾅｽｴｦｶｷｹﾒﾏｻﾂｵﾘｱﾍﾃﾜﾉﾖｽﾌﾔﾖﾙﾚﾛﾝ0123456789Z$+-*/=^~<>[]()',
        'trail_opacity': 100, 'trail_width': 2, 'turbulence_freq': 0.05, 'turbulence_strength': 0.5,
        'val_variance': 0.0, 'vortex_center_x': 400, 'vortex_center_y': 300, 'vortex_radius': 300.0,
        'vortex_strength': 2.0, 'wind': 0.0
    },
    "nova": {
        "count": 100, "interval": 999, "duration": 1, "life_min": 40, "life_max": 40,
        "emitter_type": "ring", "use_custom_rect": True,
        "radial_accel": 5.0, "gravity": 0, "drag": 0.05,
        "speed_min": 0, "speed_max": 0, "angle_min": 0, "angle_max": 360,
        "shape": "circle", "size_min": 4, "size_max": 8,
        "color": ["#00ffff"], "color_curve": None,
        "tint_image": False, "blend_mode": "add",
        "scale_curve": [1.0, 2.0, 0.0, 0.0, 0.0],
        "alpha_curve": [255, 255, 0, 0, 0],
        "trail_length": 5
    },
    "portal": {
        "count": 5, "interval": 1, "duration": -1, "life_min": 60, "life_max": 100,
        "emitter_type": "circle", "use_custom_rect": True,
        "gravity": 0, "drag": 0.0,
        "tangential_accel": 5.0, "radial_accel": -1.0,
        "speed_min": 1, "speed_max": 3, "angle_min": 0, "angle_max": 360,
        "shape": "circle", "size_min": 10, "size_max": 20,
        "color": ["#AA00FF", "#5500FF"], "color_curve": None,
        "hue_variance": 0.1,
        "blend_mode": "add", "scale_curve": [0.1, 1.0, 0.0, 0.0, 0.0]
    },
    "laser_wall": {
        "count": 10, "interval": 1, "duration": -1, "life_min": 10, "life_max": 20,
        "emitter_type": "line", "use_custom_rect": True,
        "gravity": 0.5, "speed_min": 0, "speed_max": 0,
        "shape": "rect", "size_min": 4, "size_max": 4,
        "color": ["#FF0000"], "color_curve": None,
        "blend_mode": "add",
        "trail_length": 5, "trail_width": 4, "trail_opacity": 150
    },
    "fairy_dust": {
        "count": 2, "interval": 3, "duration": -1, "life_min": 100, "life_max": 200,
        "emitter_type": "circle", "use_custom_rect": False,
        "gravity": -0.1, "drag": 0.05,
        "speed_min": 0.5, "speed_max": 1.5, "angle_min": 0, "angle_max": 360,
        "shape": "star", "star_points": 4, "size_min": 10, "size_max": 20,
        "spin_min": -5, "spin_max": 5,
        "color": ["#FFFFFF"], "color_curve": None,
        "hue_variance": 1.0,
        "blend_mode": "add",
        "alpha_curve": [0, 255, 255, 255, 0],
        "scale_curve": [0.0, 1.0, 1.0, 1.0, 0.0],
        "behaviors": ["turbulence"], "turbulence_strength": 0.3, "turbulence_freq": 0.1
    },
    "splash": {
        "count": 5, "interval": 999, "duration": 1, "life_min": 10, "life_max": 25,
        "emitter_type": "point",
        "gravity": 0.4, "drag": 0.0,
        "speed_min": 3, "speed_max": 6, "angle_min": 200, "angle_max": 340,
        "shape": "circle", "size_min": 2, "size_max": 4,
        "color": ["#a8d8ea", "#ffffff"], "color_curve": None,
        "blend_mode": "normal",
        "alpha_curve": [255, 255, 0, 0, 0],
        "scale_curve": [1.0, 0.8, 0.3, 0.0, 0.0],
        "collides": False
    },
    "mouse_trail_magic": {
        "count": 4, "interval": 1, "duration": -1, "life_min": 60, "life_max": 120,
        "emitter_type": "rect", "use_custom_rect": False,
        "gravity": 0.0, "drag": 0.1,
        "speed_min": 0.0, "speed_max": 0.0,
        "shape": "star", "star_points": 5, "size_min": 15, "size_max": 25,
        "spin_min": -3, "spin_max": 3,
        "color": ["#ffffff"], "color_curve": None,
        "hue_variance": 0.5,
        "blend_mode": "add",
        "alpha_curve": [0, 255, 200, 0, 0],
        "behaviors": ["mouse_interaction"],
        "mouse_strength": 2.0,
        "mouse_radius": 300.0,
        "mouse_mode": "attract",
        "mouse_falloff": "smooth",
        "mouse_click_only": False
    },
    "starfield": {
        "count": 2, "interval": 5, "duration": -1, "life_min": 300, "life_max": 600,
        "emitter_type": "rect", "use_custom_rect": False,
        "gravity": 0.0, "wind": 0.0, "drag": 0.01,
        "speed_min": 0.5, "speed_max": 1.5, "angle_min": 0, "angle_max": 360,
        "shape": "circle", "size_min": 2, "size_max": 5,
        "color": ["#FFFFFF"],
        "color_curve": ["#ffffff", "#ffffaa", "#ffffff", "#ffffff", "#ffffff"],
        "alpha_curve": [0, 255, 255, 255, 0],
        "scale_curve": [0.5, 1.0, 1.0, 1.0, 0.5],
        "blend_mode": "add",
        "behaviors": ["turbulence"],
        "turbulence_strength": 0.1, "turbulence_freq": 0.05
    },
    "aurora": {
        "count": 10, "interval": 2, "duration": -1, "life_min": 120, "life_max": 240,
        "emitter_type": "rect", "use_custom_rect": False,
        "gravity": -0.2, "drag": 0.05,
        "speed_min": 1, "speed_max": 3, "angle_min": 80, "angle_max": 100,
        "shape": "rect", "size_min": 50, "size_max": 100,
        "spin_min": -2, "spin_max": 2,
        "color": ["#00ff00"],
        "color_curve": ["#00ff00", "#00ffff", "#ff00ff", "#00ff00", "#00ff00"],
        "alpha_curve": [50, 150, 150, 150, 50],
        "scale_curve": [1.0, 1.5, 1.5, 1.5, 1.0],
        "blend_mode": "add",
        "trail_length": 20, "trail_width": 10, "trail_opacity": 80,
        "behaviors": ["turbulence"],
        "turbulence_strength": 0.5, "turbulence_freq": 0.02
    },
    "glowing_trail": {
        "count": 5, "interval": 1, "duration": -1, "life_min": 30, "life_max": 60,
        "emitter_type": "rect", "use_custom_rect": False,
        "gravity": 0.0, "drag": 0.1,
        "speed_min": 0.0, "speed_max": 0.0,
        "shape": "circle", "size_min": 10, "size_max": 20,
        "color": ["#ffff00"], "color_curve": None,
        "blend_mode": "add",
        "alpha_curve": [255, 255, 200, 100, 0],
        "behaviors": ["mouse_interaction"],
        "mouse_mode": "attract",
        "mouse_strength": 2.0,
        "mouse_radius": 200.0,
        "mouse_falloff": "smooth",
        "mouse_click_only": False
    },
    "fairy_swarm": {
        "count": 3, "interval": 2, "duration": -1, "life_min": 60, "life_max": 120,
        "emitter_type": "circle", "use_custom_rect": False,
        "gravity": 0.0, "drag": 0.05,
        "speed_min": 2, "speed_max": 4, "angle_min": 0, "angle_max": 360,
        "shape": "star", "star_points": 5, "size_min": 15, "size_max": 25,
        "spin_min": -3, "spin_max": 3,
        "color": ["#FFFFFF"],
        "color_curve": ["#ffffff", "#aa00ff", "#ffffff", "#aa00ff", "#ffffff"],
        "hue_variance": 0.3, "blend_mode": "add",
        "behaviors": ["mouse_interaction"],
        "mouse_mode": "orbit",
        "mouse_strength": 1.5,
        "mouse_radius": 150.0,
        "mouse_falloff": "quadratic",
        "mouse_click_only": False
    },
    "energy_orbs": {
        "count": 4, "interval": 3, "duration": -1, "life_min": 90, "life_max": 180,
        "emitter_type": "ring", "use_custom_rect": False,
        "gravity": 0.0, "drag": 0.03,
        "speed_min": 1, "speed_max": 3, "angle_min": 0, "angle_max": 360,
        "shape": "bubble", "size_min": 20, "size_max": 30,
        "color": ["#00aaff"], "color_curve": None,
        "blend_mode": "add",
        "alpha_curve": [100, 255, 255, 255, 100],
        "behaviors": ["mouse_interaction", "vortex"],
        "mouse_mode": "vortex",
        "mouse_strength": 1.0,
        "mouse_radius": 300.0,
        "vortex_strength": 1.0, "vortex_radius": 200.0
    },
    "tornado": {
        "behaviors": ["vortex"],
        "vortex_center": (400, 300),
        "vortex_strength": 3.0,
        "vortex_radius": 350,
        "count": 5,
        "gravity": 0,
        "color": ["#CCCCCC", "#FFFFFF"], "color_curve": None,
        "life_min": 120,
        "life_max": 180
    },
    "flamethrower": {
        "emitter_type": "cone",
        "cone_direction": 0,
        "cone_angle": 30,
        "count": 5, "interval": 1,
        "speed_min": 8, "speed_max": 12,
        "life_min": 20, "life_max": 40,
        "size_min": 8, "size_max": 15,
        "color": ["#FF6600", "#FF0000", "#FFAA00"], "color_curve": None,
        "gravity": -0.2, "drag": 0.05,
        "fade_in_time": 3, "fade_out_time": 15,
        "blend_mode": "add",
        "behaviors": ["turbulence"], "turbulence_strength": 0.5
    },
    "laser_bolt": {
        "emitter_type": "point",
        "count": 1,
        "shape": "rect",
        "size_min": 20, "size_max": 20,
        "speed_min": 15, "speed_max": 15,
        "angle_min": 0, "angle_max": 0,
        "life_min": 30, "life_max": 30,
        "stretch_factor": 4.0,
        "color": ["#00FFFF"], "color_curve": None,
        "blend_mode": "add",
        "trail_length": 8, "trail_width": 3,
        "gravity": 0, "drag": 0
    },
    "pixel_explosion": {
        "emitter_type": "grid",
        "grid_rows": 5, "grid_cols": 5,
        "count": 1, "interval": 1, "duration": 1,
        "shape": "rect",
        "size_min": 4, "size_max": 4,
        "speed_min": 3, "speed_max": 8,
        "life_min": 30, "life_max": 60,
        "color": ["#FF00FF", "#00FFFF", "#FFFF00", "#FF0000"], "color_curve": None,
        "gravity": 0.3,
        "fade_out_time": 20,
        "blend_mode": "add"
    },
    "spiral_galaxy": {
        "emitter_type": "spiral",
        "spiral_speed": 0.3,
        "count": 2, "interval": 1,
        "shape": "circle",
        "size_min": 3, "size_max": 6,
        "speed_min": 0.5, "speed_max": 1.5,
        "life_min": 180, "life_max": 240,
        "color": ["#FFFFFF", "#AAAAFF", "#FFAAFF"], "color_curve": None,
        "gravity": 0, "drag": 0.01,
        "fade_in_time": 10, "fade_out_time": 30,
        "blend_mode": "add",
        "behaviors": ["orbit"], "orbit_speed": 0.02
    },
    "rocket_trail": {
        "emitter_type": "point",
        "count": 1, "interval": 3,
        "shape": "circle",
        "size_min": 8, "size_max": 12,
        "speed_min": 10, "speed_max": 10,
        "angle_min": 90, "angle_max": 90,
        "life_min": 60, "life_max": 80,
        "color": ["#FF6600"], "color_curve": None,
        "gravity": -0.1,
        "on_spawn_effect": "sparkle_trail",
        "on_death_effect": "explosion",
        "trail_length": 15, "trail_width": 4,
        "blend_mode": "add"
    },
    "sparkle_trail": {
        "emitter_type": "point",
        "count": 3,
        "shape": "star", "star_points": 4,
        "size_min": 2, "size_max": 5,
        "speed_min": 0.5, "speed_max": 2,
        "angle_min": 0, "angle_max": 360,
        "life_min": 15, "life_max": 30,
        "color": ["#FFFF00", "#FFFFFF"], "color_curve": None,
        "gravity": 0.1,
        "fade_out_time": 10,
        "blend_mode": "add"
    },
    "gentle_smoke": {
        "emitter_type": "rect",
        "count": 2, "interval": 5,
        "shape": "circle",
        "size_min": 15, "size_max": 25,
        "speed_min": 0.5, "speed_max": 1.5,
        "angle_min": 80, "angle_max": 100,
        "life_min": 120, "life_max": 180,
        "color": ["#888888", "#AAAAAA", "#CCCCCC"], "color_curve": None,
        "gravity": -0.05, "drag": 0.02,
        "fade_in_time": 20, "fade_out_time": 40,
        "scale_curve": [0.5, 1.0, 1.5, 2.0],
        "behaviors": ["turbulence"], "turbulence_strength": 0.3
    },
    "machinegun": {
        "emitter_type": "cone",
        "cone_direction": 0, "cone_angle": 10,
        "count": 1, "interval": 3,
        "shape": "rect",
        "size_min": 3, "size_max": 4,
        "speed_min": 20, "speed_max": 25,
        "stretch_factor": 3.0,
        "life_min": 20, "life_max": 25,
        "color": ["#FFFF00"], "color_curve": None,
        "gravity": 0,
        "blend_mode": "add",
        "trail_length": 5, "trail_width": 2
    },
    "warp_portal": {
        "emitter_type": "ring",
        "count": 8, "interval": 2,
        "shape": "star", "star_points": 4,
        "size_min": 5, "size_max": 10,
        "speed_min": 3, "speed_max": 5,
        "life_min": 40, "life_max": 60,
        "color": ["#00FFFF", "#FF00FF"], "color_curve": None,
        "gravity": 0,
        "radial_accel": -2.0,
        "fade_in_time": 5, "fade_out_time": 15,
        "blend_mode": "add",
        "behaviors": ["vortex"],
        "vortex_strength": 3.0, "vortex_radius": 200,
        "vortex_center": (0, 0)
    }
}